// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Antes se lanzaba una excepción al no tener opciones web.
      // Para evitar la pantalla en blanco en entornos web devolvemos
      // unas opciones basadas en la configuración Android ya presente.
      // Si quieres una configuración específica para web, genera
      // `firebase_options.dart` con FlutterFire CLI y reemplaza esto.
      return FirebaseOptions(
        apiKey: android.apiKey,
        appId: android.appId,
        messagingSenderId: android.messagingSenderId,
        projectId: android.projectId,
        storageBucket: android.storageBucket,
        authDomain: '${android.projectId}.firebaseapp.com',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZcipEsJwTf2MtmKDzOtFdESlcgOWhHgU',
    appId: '1:1001834132065:android:54f19983a03707427c7020',
    messagingSenderId: '1001834132065',
    projectId: 'sistemagamificacion',
    storageBucket: 'sistemagamificacion.firebasestorage.app',
  );
}
